version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.18.1
    steps:
      - checkout
      - run:
          name: Install
          command: yarn
      - run:
          name: Test
          command: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
